load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_binary(
    name = "primitive_default_construction",
    srcs = ["primitive_default_construction.cc"],
)

cc_binary(
    name = "const_ref_cast",
    srcs = ["const_ref_cast.cc"],
)
