load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_binary(
    name = "primitive_default_construction",
    srcs = ["primitive_default_construction.cc"],
)

cc_binary(
    name = "const_ref_cast",
    srcs = ["const_ref_cast.cc"],
)

cc_binary(
    name = "base_class_ref",
    srcs = ["base_class_ref.cc"],
)

cc_binary(
    name = "stl_test",
    srcs = ["stl_test.cc"],
)

cc_binary (
    name = "copy_lambda",
    srcs = ["copy_lambda.cc"],
)

cc_binary (
    name = "binary_search",
    srcs = ["binary_search.cc"],
)

cc_binary (
    name = "reference_hack",
    srcs = ["reference_hack.cc"],
)

cc_binary (
    name = "copy_elision",
    srcs = ["copy_elision.cc"],
)

cc_binary (
    name = "value_init",
    srcs = ["value_init.cc"],
)

