load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")

cc_binary(
    name = "template_class_test",
    srcs = ["template_class_test.cc"],
)

cc_binary(
    name = "perfect_forward",
    srcs = ["perfect_forward.cc"],
)

cc_binary(
    name = "parameter_pack",
    srcs = ["parameter_pack.cc"],
)

